---
title: "About Statistics of Disease Dynamics "
author: "LiJin Joo [lijin.joo at gmail.com](mailto:lijin.joo@gmail.com)"
date: '2020-10-12'
output:
  pdf_document: default
  html_document: default
bibliography: covid19.bib
---

Reproduction number (R) and epidemic growth rate (r) are two statistics to describe disease dynamics, or transmission of COVID-19. Each of them measures a different aspect of disease dynamics, thus neither of them can be replaceable with the other. Reproduction number R tells about a direction of growth, whether an epidemic is growing or shrinking, yet does not tell how fast a number of cases is growing at each time point. On the other hand, a growth rate r provides the information about size and speed of change at one time point but does not predict how likely a number of cases will grow or decline for the next time point. The goal of presenting these two statistics is to assess the effectiveness of a public health intervention, such as community lockdown, and to assist decision making for relaxing, or strengthening an intervention based on most recent data [@royal2020Randr] [@govUK2020Randr].

## Reproduction Number (R)
The reproduction number (R) is an average number of secondary infections produced by a single infected person and shows the potential of transmission. 
If R is greater than 1, every infected patient would produce more than one new case on average, thus the disease continues to spread. If R is smaller than 1, a new case from an existing patient is less than one on average, the disease would shrink and eventually stop. 


Initially, a basic reproduction number, R0, is designed for measuring a potential of disease transmission at the beginning of an epidemic, assuming a population never exposed to a pathogen [@delamater2019complexity]. However, in reality, it takes some time for an epidemic to be manifested. To estimate a number of secondary infections from a small number of initial cases, complex mathematical models under various sets of assumptions are necessary. One well known model for separating secondary infections from observed case is ``susceptible, incubation, infectious and recovered (SEIR) model”, which models each of the four populations using a series of ordinary differential equations [@royal2020Randr].


Among variations, we used a version of R, called “time-varying” reproduction number, which concerns more about how disease transmissibility evolves over time, rather than inherent biological characteristics of a pathogen. As infectious cases accumulate over time, cases grow faster with more cases from all of susceptible, exposed and recovered populations, yet the speed of growth would slow down over time within a population of a finite size. Therefore, Rt is always smaller than R0.


For Rt, we used the method developed by [@cori2013new], which takes a series of incidences only and learns the values of necessary parameters from its empirical density and Bayesian model assumptions. The formulas are provided by R package {EpiEstim} and {EpiNow2}.

* The formula for Rt from {EpiEstim} is as follows.
$$  R_t = \frac{I_t}{\sum_{s=1}^{t} I_{t-s} \omega_s} $$ 
where $I_t$ is an incidence at time $t$ and $\omega$ is a discounting weight for an incidence at time $s$ at the present time $t$ ($s < t$). This weight is estimated from an empirical density called ``serial intervals”, an average time between the first symptom of a transmitter and that of newly infected. To be compatible to the Poisson model for case series, a conjugate Gamma model is used.  The Poisson model predicts a number of new cases at time $t$, $I_t$ by approximation with a series of incidences as below.

$$ P(I_t | I_0, I_1, \dots, I_{t-1}, \omega, R_t) = \frac{(R_t \Lambda_t)^{I_t}}{I_t !}$$
with  $\Lambda_t = \sum_{s=1}^{t} I_{t-s} \omega_s$.

* As $I_t$ is a stochastic process, so $R_t$ is. At time $t$, $R_t$ is right censored due to the unreported cases for 1) the delay in reporting, 2) an incubation period of a new case, 3)  a generation time, a time between infection events. These three parameters are additionally considered in {EpiNow2} by [@abbott2020estimating], which contribute to the better uncertainty estimates for Rt. 

* We used estimate_R() function with a ``parametric_si” option assuming a gamma prior with a mean of 4 days and a standard deviation of 4.75 days and 7 days of smoothing window  suggested by [@abbott2020estimating],  [@Basu2020]. However, Bayesian estimates give unreasonably small variations (sd < 0.01) for recent data where Rt is lingering around 1 with a large number of new cases.    



## Growth Rate (r) 
The growth rate r is calculated by the second order derivative of an incidence (generating) function and indicates how quickly infections are changing at time point $t$. A growth rate also shows how many new cases are occurring for the next time point, usually under the exponential growth assumption for an infectious disease and can serve an instantaneous indicator for the impact of a public health intervention. If the growth rate is greater than zero (or positive), the epidemic is growing. If the growth rate is less than zero (or negative) then the epidemic is declining [@royal2020Randr]. 

* Calculation of $r$ is simple and does not require a model as in $Rt$. However, cares must be taken to interpret the size of $r$ on an epidemic growth curve. For instance, two times greater $r$ with a small number of new cases with a larger $Rt$, a growing phase of an epidemic, is a more critical situation than a two times greater $r$ with more new cases but with a smaller $Rt$ at the stabilization phase of an epidemic. To enhance the interpretability of $r$, we provide two more statistics. 

* Doubling Time ($d_t$): we used the formula from [@Basu2020] as follows.
$$ d_t = \tau \frac{log(2)}{log(1+r)} $$ 
where the growth rate $r$ is given by 
$$ r = \frac{I_{t} - I_{t-1}}{I_{t-1}}$$
for $t = 0, 1, \dots, T$ and $\tau$ is a window size of smoothing. We used $\tau =$ 7 days.  
A doubling time estimates a time to take a number of cases today to be twice in future based on the current growth rate $r$ estimated by new cases within a window size $\tau$, in our case over the fast week. Given that a growth rate of today is reflecting the data of previous 7 days, a doubling time relates the past observation to the prediction for future. 

* Levitt Statistics: Levitt statistics is an alternative way to see a change of cases [@levitt2020predicting].
 $$ H(t) = log(\frac{X_t}{X_{t-1}}) $$
where $X_t$ is cumulative cases upto day $t$.  While a growth rate $r$ represents an instantaneous rate change of cases at each day, Levitt’s statistics calculates a change in cases with cumulative cases and this shows how a number of cases are changing, or the first of change). If $H(t) < 0$, cases are decreasing. If $H(t) > 0$, cases are increasing. 

We compute Levitt statistics for deaths only followed the suggestion by [@raman2020will]. When a number of incidences are capped by testing capacity, an incidence series does not capture an epidemic growth accurately. Deaths are less prone to this type of confounding effect, which causes censoring cases by testing capacity.   




  
---
nocite: |
  @Gostic2020, @obadia2012r0, @wallinga2004different
...

### Reference





